### ISSUE TITLE
Google Cast - les icônes ne s'affichent pas

### ISSUE THREAD

**Issue by bubizar** [hacf-fr/lovelace-meteofrance-weather-card#100]
Beau travail. 🤩👏
C'est pour cette raison d'ailleurs que je souhaitais pouvoir caster 📺 le dashboard et profiter de l'info ☔ pluie dans l'heure ☔ .

Tout fonctionne sauf les **icônes animées qui ne sont pas affichées**. 😿

Merci pour l'intérêt porté à ce post.

**Comment by Tays005** [comment]
Effectivement j'ai le même soucis dommage,

**Comment by Tays005** [comment]
Bonjour, je les veux bien si pouvez pour faire le test ^^

**Comment by Axellum** [comment]
Salut, je regarde ce soir pour te donner le lien. Sinon j ai mis un lien sur le forum.

**Comment by Axellum** [comment]
Re,
sur ce lien tu trouvera deux jeux d’icônes supplémentaire:
[Icones en sup](https://github.com/Axellum/lovelace-meteofrance-weather-card/tree/Meteo-France/dist)
Normalement ils devrait coller pile poil a la carte, je les avez fais pour, si tu as un pb dit le moi.

**Comment by Axellum** [comment]
[izeau](https://github.com/izeau) commented [Jan 24, 2022](https://github.com/hacf-fr/lovelace-meteofrance-weather-card/issues/77#issuecomment-1019922649)

On peut remplacer les icônes animées par des icônes fixes assez simplement en configurant Icons location à https://cdn.jsdelivr.net/gh/hacf-fr/lovelace-meteofrance-weather-card@latest/icons/static/.

**Comment by Tays005** [comment]
Merci beaucoup Axellum !

**Comment by dx44** [comment]
Si je comprends bien, les icônes de type animés ne s'affichent pas sur un Google Cast ?
Par contre les svg statiques oui ?
Dans ce cas une amélioration pourrait se faire pour avoir un jeu d'icônes statiques. A voir si il existe un moyen de détecter ce comportement ou tout simplement placer un switch dans la configuration de la carte 🤔

**Comment by Axellum** [comment]
Salut,
j'ai le lots d’icônes bleus statistique de prête si jamais.
Je peu mettre aussi à disposition les même icônes en blancs, animées et statiques, cela pourrait donner un plus à la carte si switch il y as :).

**Comment by dx44** [comment]
Ah oui mais il faudrait le switch avec 😉

**Comment by Axellum** [comment]
Bon, j'ai toujours pas prit de cours de codage ^^. J’essaie de voir ce que je peu faire en fin de semaine.

**Comment by Axellum** [comment]
De souvenir, on avaient ajouter deux icônes supplémentaire (orage et brouillard??). Je crois que le cadrage est aussi un peu différent...

**Comment by dx44** [comment]
Corrigé en [Pre-release 1.9.0-6](https://github.com/hacf-fr/lovelace-meteofrance-weather-card/releases/tag/1.9.0-6).
Intégré à la prochaine release ce week-end !

**Comment by Axellum** [comment]
Parfais, les icônes sont par contre un peu plus petites que les animées. 
(ligne 2 sont les nouvelle, ligne 1 les animée, 3 le fixe fais à partie du jeux animé).

![Capture d’écran 2023-05-06 ico](https://user-images.githubusercontent.com/60935256/236608687-7853f03b-15b7-4e2f-a7ed-4bd0cb7c52dd.png)

Si jamais les blanc dispo (2 fixe):

![Capture d’écran 2023-05-06 ico bl](https://user-images.githubusercontent.com/60935256/236608872-14272f5b-0d81-447e-927e-1af9de03f093.png)

**Comment by dx44** [comment]
La cohérence du thème bleu est pour le moment gardé et effectivement les icônes statiques sont affichés plus petits 🤔
Je n'ai pas plus de tems ces prochains jours pour creuser ça mais à mettre dans une nouvelle issue car la partie icônes statiques est publiée.
