### ISSUE TITLE
Les icones ne s'affichent pas

### ISSUE THREAD

**Issue by Ma-Maison-Intelligente** [hacf-fr/lovelace-meteofrance-weather-card#101]
Résolu ! Voir la fin du message ci-dessous

Bonjour. 
Merci pour le partage et bravo pour le travail réalisé.

J'ai installé la carte en suivant les explications mais les icones n'apparaissent pas.
![image](https://user-images.githubusercontent.com/122357036/212129421-c09a97de-e6a3-496d-8f41-974ac1fbdb17.png)
Pourriez vous me donner la marche à suivre pour avoir la carte avec les icones comme celle présentée dans le les explications.

D'avance merci. 

Solution: 
Les icones s'affichent quand le paramétrage de l'intégration (menu Paramètre / Appareils et Services onglet Intégration puis bouton Configurer de l'intégration météo-France) est configuré en "hourly"
![image](https://user-images.githubusercontent.com/122357036/212153575-f6b583d2-9663-4369-8695-8d593bdd6b36.png)

Le résultat après redémarrage de Home Assistant: Les icones sont présentes.
![image](https://user-images.githubusercontent.com/122357036/212154120-bdd8d358-1b26-4084-80a3-8ac5c7f9c912.png)

**Comment by Axellum** [comment]
Hum,  je n avais pas vus ce pb.

<img width="393" alt="Capture d’écran 2023-03-13 195336" src="https://user-images.githubusercontent.com/60935256/224801847-354cd986-385b-4502-a998-a754085acdc2.png">
