### ISSUE TITLE
Mauvaise icone en journée beta 1.9.0-1.

### ISSUE THREAD

**Issue by WarC0zes** [hacf-fr/lovelace-meteofrance-weather-card#105]
Bonjour,
j'ai installer la version beta 1.9.0-1 et il y a un problème sur l'icone principal, qui n'est pas la bonne.
![meteo bad icon](https://user-images.githubusercontent.com/91471397/236504107-f1dd710e-bdd0-4d84-957e-119189dc36e4.png)

**Comment by dx44** [comment]
Quel est le nom du svg affiché dans ta capture ?

**Comment by WarC0zes** [comment]
c'est night.svg
![meteo bad icon2](https://user-images.githubusercontent.com/91471397/236506706-79217744-9248-4054-82d0-715d23344091.png)

**Comment by dx44** [comment]
Bon c'est normal, la méthode de calcul des icônes n'a pas été appliquée pour le détails de la carte.

**Comment by dx44** [comment]
Corrigé en [Pre-release 1.9.0-6](https://github.com/hacf-fr/lovelace-meteofrance-weather-card/releases/tag/1.9.0-6).
Intégré à la prochaine release ce week-end !

**Comment by WarC0zes** [comment]
> Corrigé en [Pre-release 1.9.0-6](https://github.com/hacf-fr/lovelace-meteofrance-weather-card/releases/tag/1.9.0-6). Intégré à la prochaine release ce week-end !

C'est bon pour l'icone pour le détail de la carte. 
Par contre je remarque que les icones sont plus animées, mais surprise je me rend compte qu'il y a une nouvelle option `static_icons:`. Donc c'est pas un bug mais une nouveauté qui n'est pas annoncée et pas documenté, faudras mettre a jour la doc.
