### ISSUE TITLE
Affichage de la vitesse du vent dans les prévisions journalières, ne s'affiche pas.

### ISSUE THREAD

**Issue by WarC0zes** [hacf-fr/lovelace-meteofrance-weather-card#106]
Bonjour,
je viens de remarquer que la vitesse du vent ne s'affiche pas pour la météo par jours.
![pas de vent](https://user-images.githubusercontent.com/91471397/236659388-c42bf597-307f-4665-a284-c950ec5fcfb7.png)

Pourtant c'est annoncé comme possible:

**Feature(s)** :

Ajout de l'affichage de la vitesse du vent dans les prévisions horaires ou **journalières**

Mon entité météo est bien configurer sur daily.
Un bug ou un soucis d'annonce ?

**Comment by dx44** [comment]
Effectivement, la donnée ne semble pas exister pour les prévisions à x jours.
Je vois pour modifier l'annonce. Merci !
