### ISSUE TITLE
Consommation intensive de ressource

### ISSUE THREAD

**Issue by nash68** [hacf-fr/lovelace-meteofrance-weather-card#107]
Bonjour,
superbe carte météo.
Par contre je viens de m'apercevoir qu'elle génère une consommation excessive d'énergie sur  ma tablette. La batterie se vide très vite. En retirant la carte, tout revient à la normale.

**Comment by nash68** [comment]
Non, mais je vais le faire et je te dirai.

**Comment by nash68** [comment]
> bonjour, ta essayer de mettre les icones en statique au lieu de animé?

Hello. Comment faire cela ?

**Comment by WarC0zes** [comment]
> > bonjour, ta essayer de mettre les icones en statique au lieu de animé?
> 
> Hello. Comment faire cela ?

Il te faut la dernière version 1.9.0
soit tu ajoute le code a ta carte (yaml):
```
static_icons: true
```
ou en mode UI, par l'editeur de la carte.
![static icon](https://user-images.githubusercontent.com/91471397/236980686-cb77400f-9ce7-4933-b952-7f66ba4eefb9.png)

**Comment by nash68** [comment]
Ok. Cela fonctionne en supprimant les icônes animées. Merci !
