### ISSUE TITLE
Plus d'heure afficher dans les détails (more-info).

### ISSUE THREAD

**Issue by WarC0zes** [hacf-fr/lovelace-meteofrance-weather-card#116]
Bonjour,
suite a la maj du core 2023.8.0, je me suis rendu compte qu'il n'y avait plus l'heure afficher dans les détails de la météo. L'entité météo est configurer sur `daily`
Aussi, qu'un trait a coté de la température est apparu. Toujours dans les détails.

![carte bug 2023 8 0](https://github.com/hacf-fr/lovelace-meteofrance-weather-card/assets/91471397/6fefab99-fd56-4be2-ba6a-9da9dd71116f)

edit:
peu être plus un soucis de l'intégration ?

**Comment by WarC0zes** [comment]
https://github.com/home-assistant/core/issues/97842
Un problème de fronted, qui sera fix pour la 2023.8.2

**Comment by Fr4mby** [comment]
En ce qui me concerne, j'ai toujours le souci après installation de la 2023.8.2.

**Comment by WarC0zes** [comment]
Idem, mais le fix est pas inclus dans la 2023.8.2. Faut attendre une maj du fronted.
https://github.com/home-assistant/frontend/pull/17440

**Comment by WarC0zes** [comment]
@Fr4mby c'est fix avec le core 2023.8.3.

**Comment by Fr4mby** [comment]
Je l'ai constaté ce matin :)
Merci pour l'info!
