### ISSUE TITLE
Les alertes météo semblent HS

### ISSUE THREAD

**Issue by nash68** [hacf-fr/lovelace-meteofrance-weather-card#117]
Bonjour,
les alerte météo ne fonctionnent plus chez moi. 
Dans le doute j'ai créé un nouvelle carte pour Paris, mais toujours pas d'alertes.
Cela fonctionne chez vous ?
Merci.

**Comment by bobdesbois** [comment]
> Bonjour, les alerte météo ne fonctionnent plus chez moi. Dans le doute j'ai créé un nouvelle carte pour Paris, mais toujours pas d'alertes. Cela fonctionne chez vous ? Merci.

Bonjour,
J'ai le même souci, et en ce moment je suis dans un département avec alerte canicule. 
De ce que j'ai lu en parcourant ici et là c'est que Météo France a changé qqc et que le du coup l'intégration Météo-France ne fonctionne plus correctement au niveau des alertes.

**Comment by WarC0zes** [comment]
Bonjour,
les alertes météo france sont cassées depuis plus de 3 mois. Météo france a changer D'api en V2, faut que les devs mette a jours l'intégration.

**Comment by dx44** [comment]
Le problème n'est pas dans ce projet mais dans celui de [meteofrance-api](https://github.com/hacf-fr/meteofrance-api).
