### ISSUE TITLE
Carte n'est plus 100% compatible avec l'intégration MF dès 2023.9

### ISSUE THREAD

**Issue by vingerha** [hacf-fr/lovelace-meteofrance-weather-card#120]
Recupération "forecast" a changé de manière importante et c'est la carte qui doix gérer si daily / hourly 
La carte ne montre que 'daily' (2023.9)
https://rc.home-assistant.io/blog/2023/08/30/release-20239/#weather-forecast-service

**Comment by Bastiencc** [comment]
+1

**Comment by WarC0zes** [comment]
Bonjour,
j'ai toujours la météo qui s'affiche par heure ou jours pour les sensors déja configurer. Mais on peu plus choisir dans la configuration de météo-france par heure ou jours, c'est la carte qui doit le faire. 
Voulant supprimer une ville, je peu pas utiliser le même sensor météo pour heure ou jour.

**Comment by vingerha** [comment]
WORKAROUND (via le forum HA), create your own sensor
```
template:
  - trigger:
      - platform: time_pattern
        hours: /1
    action:
      - service: weather.get_forecast
        data:
          type: hourly
        target:
          entity_id: weather.yoursensor
        response_variable: hourly
    sensor:
      - name: Weather Forecast Hourly
        unique_id: weather_forecast_hourly
        state: "{{ now().isoformat() }}"
        attributes:
          forecast: "{{ forecast }}"

**Comment by Bastiencc** [comment]
@vingerha tu as le lien du topic original stp ?

**Comment by vingerha** [comment]
Aussi sur HACF j'ai posté ça
https://www.home-assistant.io/integrations/template/#trigger-based-handling-of-service-response-data

**Comment by dx44** [comment]
La dernière release doit corriger https://github.com/hacf-fr/lovelace-meteofrance-weather-card/releases/tag/1.9.2-beta-2
