### ISSUE TITLE
Où se trouvent les "Sensors" Soleil

### ISSUE THREAD

**Issue by JacVid** [hacf-fr/lovelace-meteofrance-weather-card#121]
Bonjour,
je suis nouveau dans le monde HA (je viens de HomeBridge). J'apprécie cette carte, mais je souhaiterai pouvoir supprimer les infos de levé et couché de soleil, car je fais apparaitre ces données ailleurs.
J'ai cherché les solutions de personnalisation, mais je ne trouve pas la référence à ces données pour les placer en masqué.
Merci pour vos retours.

**Comment by dx44** [comment]
Bonjour,
Cette personnalisation n'est pas possible à ce jour. L'information est automatiquement affichées dès que le sensor sun existe.
