### ISSUE TITLE
Icones non chargées

### ISSUE THREAD

**Issue by Peter86000** [hacf-fr/lovelace-meteofrance-weather-card#127]
Bonjour,

j'ai installé HA sur un Khadas VIM1S, fonctionne parfaitement.
J'ai maintenant installé lovelace-meteofrance-weather-card qui fonctionne correctement à un détail près :  les icônes n'apparaissent pas.

Dans le code HTML ils sont appelés à l'URL     "/local/community/lovelace-meteofrance-weather-card/icons/"
Dans l'arborescence ils sont dans "/root/config/www/community/lovelace-meteofrance-weather-card/icons/"

Je n'arrive dans tous les cas pas à les appeler directement par exemple avec :
https://monadresse/community/lovelace-meteofrance-weather-card/icons/rainy-5.svg
https://monadresse/local/community/lovelace-meteofrance-weather-card/icons/rainy-5.svg
...

Auriez-vous une idée ?

Merci !

**Comment by Peter86000** [comment]
- Dans Paramètres --> "Appareils et services" --> "Intégrations"
- "Météo France" --> "1 service" --> "Ajouter au tableau de bord"
- Sur la carte ajoutée --> "Modifier" --> activer le bouton "Colorer les icônes en fonction de l'état"

**Comment by loiiiic** [comment]
Bonjour,
J'ai le même soucis. Le fait d'activer l'option "Colorer les icônes en fonction de l'état" n'a rien changé chez moi.

**Comment by loiiiic** [comment]
Après redémarrage d'Home Assistant, les icônes sont maintenant visibles.

Si on désactive l'option "Colorer les icônes en fonction de l'état" et qu'on redémarre Home Assistant cela fonctionne également. Du coup, je pense qu'il n'y a pas besoin de faire cette manip.

**Comment by Arnaud73** [comment]
Idem me concernant.
Ce fut le premier module HACS que j'ai installé.
Au départ, tout fonctionnait sauf les icones. En fait, il cherchait ses icones avec des URLs telles que `https://mon-serveur/local/community/lovelace-meteofrance-weather-card/icons/cloudy-day-3.svg` ce qui se terminait en erreur 404.
Après redémarrage complet de Home Assistant, ca fonctionne.
