### ISSUE TITLE
Possibilité de désactiver les animations

### ISSUE THREAD

**Issue by Karmak23** [hacf-fr/lovelace-meteofrance-weather-card#132]
J'utilise cette carte pour la précision de son affichage (plus de détails que dans les cartes génériques), mais j'ai besoin de désactiver les animations.

Je sais que je peux désactiver les animations complètement au niveau du navigateur, et c'est fait sur les tablettes anciennes. Maintenant pour les périphériques récents / puissants je voudrais désactiver les animations carte par carte, car je trouve l'animation inutilement distrayante, alors que sur d'autres cartes je souhaite garder l'animation car elle est liée à une action, et non juste l'affichage non-intéractif.

Exemple, sur une autre carte, `custom:hourly-weather` pour la nommer, j'ai une option `animated_icon: false` et je voudrais une option similaire pour la carte météo france. Merci pour votre retour.

**Comment by manu3b1** [comment]
Hello @Karmak23, sur la carte météo-france, il existe également l'option animated_icon.

**Comment by dx44** [comment]
Salut @Karmak23 , comme le précise @manu3b1 il y a cette option de disponible. Techniquement cela indique d'utiliser un jeu d'icônes statiques.
