### ISSUE TITLE
Supprimer direction vent forecast

### ISSUE THREAD

**Issue by JordanG55** [hacf-fr/lovelace-meteofrance-weather-card#137]
Bonjour ,
Possible de supprimer la direction du vent dans les prévisions ?
Perso je trouve que ça prend de la place pour pas grand chose .
`type: custom:meteofrance-weather-card
entity: weather.hannonville_sous_les_cotes
rainChanceEntity: sensor.hannonville_sous_les_cotes_rain_chance
uvEntity: sensor.hannonville_sous_les_cotes_uv
cloudCoverEntity: sensor.hannonville_sous_les_cotes_cloud_cover
freezeChanceEntity: sensor.hannonville_sous_les_cotes_freeze_chance
alertEntity: sensor.55_weather_alert
rainForecastEntity: sensor.hannonville_sous_les_cotes_next_rain
forecast: true
snowChanceEntity: sensor.hannonville_sous_les_cotes_snow_chance
number_of_forecasts: '5'
current: true
details: true
one_hour_forecast: true
alert_forecast: true
`

**Comment by fcarlier** [comment]
Dans ton paramétrage, tu mets `wind_forecast_icons = false`
