### ISSUE TITLE
Not compliant avec HACS 2.0.0

### ISSUE THREAD

**Issue by fcarlier** [hacf-fr/lovelace-meteofrance-weather-card#139]
Bonjour,
Message dans HACS lors de l'ajout d'un dépôt personnalisés :
"<Theme hacf-fr/lovelace-meteofrance-weather-card> Repository structure for 1.9.0 is not compliant"

Je suis avec Home Assistant Core 2024.8.2 et je viens de mettre à jour HACS en version 2.0.0.

Une solution ?

**Comment by fcarlier** [comment]
Bonsoir,
L'installation manuelle fonctionne mais je ne vais pas avoir d'interface de configuration, passage en YAML.
Par contre "custom:meteofrance-weather-card" ne fonctionne pas, j'ai bien rajouté la ressource pourtant comme indiqué ;)
Merci ...

**Comment by fcarlier** [comment]
Damned, j'installais mal dans HACS ! j'avais mis thème au lieu de Tableau de Bord !! Sorry

**Comment by WarC0zes** [comment]
Bonjour,
la version beta 1.9.2-beta-2, ne peux pas s'installer a partir de HACS 2.0

![image](https://github.com/user-attachments/assets/938bc453-0a2b-4a77-b3fe-eed8ab899d3d)

@dx44 
Tu peux voir d'où vient le problème ?
