### ISSUE TITLE
Version beta, impossible de l'installer depuis HACS 2.0

### ISSUE THREAD

**Issue by WarC0zes** [hacf-fr/lovelace-meteofrance-weather-card#140]
Bonjour,
la version beta 1.9.2-beta-2, ne peut pas s'installer à partir de HACS 2.0.
![image](https://github.com/user-attachments/assets/970202a6-c7ec-4b81-8e51-474aedc172bc)

@dx44 
Peux-tu voir d'où vient le problème ?

**Comment by fcarlier** [comment]
La 1.9.0 est dans la branche 'Meteo-France' alors que la 1.9.2 est hors branche 
"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

Donc je pense que HACS voit la branch par défaut mais pas les autres ;)

**Comment by vingerha** [comment]
@dx44 J'ai fait une copie du dossier et je pense que le nom du release n'est pas 'conforme' ... Je ne trouve pas des règles dans la docu de HACS mais ... voir 192_b2 ici
https://github.com/vingerha/lovelace-meteofrance-weather-card

**Comment by vingerha** [comment]
J'ai trouvé le soucis. Il faut ajouter un fichier hacs.json

https://hacs.xyz/docs/publish/start/?h=beta#hacsjson

**Comment by Stef42300** [comment]
> J'ai trouvé le soucis. Il faut ajouter un fichier hacs.json
> 
> https://hacs.xyz/docs/publish/start/?h=beta#hacsjson

Je n'ai pas compris du coup. On doit faire quoi pour l'installer via HACS ? Sinon en manuel comment on fait ? Si tu peux détailler stp

**Comment by vingerha** [comment]
Il fau ajouter une fichier hacs.json dans le 'root' du branch....comme ici:
https://github.com/vingerha/lovelace-meteofrance-weather-card

**Comment by WarC0zes** [comment]
> Il fau ajouter une fichier hacs.json dans le 'root' du branch....comme ici: https://github.com/vingerha/lovelace-meteofrance-weather-card
> 
> Je l'ai fait pour master et dev brranches

Tu ne pourrais pas faire un PR ?
Ça avancera le boulot pour @dx44 qui n'a plus le temps.

**Comment by vingerha** [comment]
Merci et c'est pas nécessaire de changer le format du release....si tu vire 1.9.2-b2 et le refait..ça marche aussi

**Comment by WarC0zes** [comment]
Merci @vingerha pour le PR et @dx44 pour la validation.
Ca fonctionne bien avec HACS 2.0
