### ISSUE TITLE
Positionner sur le jour courant.

### ISSUE THREAD

**Issue by sebastienserre** [hacf-fr/lovelace-meteofrance-weather-card#141]
Nous sommes dimanche et j'ai la meteo des 5 dernier jours...
![2024-09-01_10-28](https://github.com/user-attachments/assets/21b5d312-88c6-4c2c-8006-5777c889d9ef)

**Comment by WarC0zes** [comment]
Bonjour,
aucun soucis de mon coté. On est mardi
![image](https://github.com/user-attachments/assets/533d8fbe-7212-4d88-a34e-7f5254ee3936)

**Comment by sebastienserre** [comment]
Pareil ici auj'ourd'hui.

**Comment by dx44** [comment]
Bonjour @sebastienserre , le pb est-il persistant avec la dernière version ?

**Comment by sebastienserre** [comment]
Pour le moment, c'est rentré dans l'ordre @dx44 mais je vais monitorer encore jusqu'à dimanche. Je reviendrai commenter.

**Comment by sebastienserre** [comment]
Je ne reproduis plus.
Merci por ce module.
