### ISSUE TITLE
Pas de prévisions malgré la MAJ en 2024.03.0b0 

### ISSUE THREAD

**Issue by Stef42300** [hacf-fr/lovelace-meteofrance-weather-card#145]
Bonjour,

Malgré la MAJ en 2024.03.0b0 je n'ai aucune prévision qui apparait.
`type: custom:meteofrance-weather-card
entity: weather.villerest
name: Villerest
cloudCoverEntity: sensor.villerest_cloud_cover
rainChanceEntity: sensor.villerest_rain_chance
freezeChanceEntity: sensor.villerest_freeze_chance
snowChanceEntity: sensor.villerest_snow_chance
uvEntity: sensor.villerest_uv
rainForecastEntity: sensor.villerest_next_rain
number_of_hourly_forecasts: '5'
number_of_daily_forecasts: '5'
wind_forecast_icons: true
daily_forecast: true
one_hour_forecast: true
details: true
current: true
alert_forecast: true
hourly_forecast: true
humidity_forecast: true
animated_icons: true`

J'obtiens cela :
![image](https://github.com/user-attachments/assets/45015ee5-1fa8-47be-b56f-c684597df5bf)

**Comment by WarC0zes** [comment]
Salut @vingerha,
il y a un souci avec l'installation de la beta 2024.03.0b0, les prévision ne fonctionne pas pour ce qui viennent de l'installer.
Moi, j'étais en version 1.9.2-beta-2, avant la sortie de HACS 2.0. Après la sortie de HACS 2.0 et la mise vers la version 2024.03.0b0, je n'est pas eu de problème de mon côté. Les prévisions fonctionnent.

**Comment by vingerha** [comment]
@WarC0zes je ne sais pas. J'ai que ajouté le fichier 'hacs.json' pour que s'installe depuis un pre-release. Souvent avec des cartes java c'est le caching.

**Comment by WarC0zes** [comment]
@Stef42300 tu as essayer de vider le cache de ton navigateur et voir si ca fonctionne ?

**Comment by vingerha** [comment]
J'ai le même comportement dans mon Chrome ne mode incognito, c'est 99% sûre un soucis avec le browser ...vider le cache

**Comment by Stef42300** [comment]
Je suis sous Chrome et j'avais vidé le cache (CTRL + F5), pas dans le menu "Outils" par contre

**Comment by vingerha** [comment]
crt-f5 n'est pas suffisante...essaie de effacer le chache pour 'cached images and files' via Settings > Clear Cache

**Comment by Stef42300** [comment]
> ctr-f5 n'est pas suffisante...essaie de effacer le cache pour 'cached images and files' via Settings > Clear Cache

Ca ne change rien

**Comment by Stef42300** [comment]
Déjà fait et cela ne change pas le problème :
![image](https://github.com/user-attachments/assets/49a9ac36-646e-42af-b0e5-5f8d758cbcc3)

**Comment by vingerha** [comment]
Ou... essayez d'effacer le tout de HACS et vérifier que le dossier est effacé aussi et reïnstaller de 0

**Comment by Stef42300** [comment]
> Ou... essayez d'effacer le tout de HACS et vérifier que le dossier est effacé aussi et reïnstaller de 0 Si ça n'aide non plus...epuisée des idées

J'ai supprimé le dossier complètement mais ça ne change rien du tout

**Comment by DavidTre07** [comment]
Salut,
marche pas non plus chez moi.
Peut-être un problème dans notre configuration suite à des mises à jour successives ?

Voici ma conf:
```
type: custom:meteofrance-weather-card
entity: weather.nice
current: true
details: true
alert_forecast: true
one_hour_forecast: true
forecast: true
daily_forecast: true
hourly_forecast: true
humidity_forecast: true
wind_forecast_icons: true
animated_icons: true
number_of_hourly_forecasts: '5'
number_of_daily_forecasts: '5'
detailEntity: sensor.nice_daily_precipitation
cloudCoverEntity: sensor.nice_cloud_cover
rainChanceEntity: sensor.nice_rain_chance
freezeChanceEntity: sensor.nice_freeze_chance
snowChanceEntity: sensor.nice_snow_chance
uvEntity: sensor.nice_uv
rainForecastEntity: sensor.nice_next_rain
alertEntity: sensor.06_weather_alert
hide_precipitation: false
hide_alertVentViolent: false
hide_alertPluieInondation: false
hide_alertOrages: false
hide_alertInondation: false
hide_alertNeigeVerglas: false
hide_alertCanicule: false
hide_alertGrandFroid: false
hide_alertAvalanches: true
hide_alertVaguesSubmersion: false
```
Si quelqu'un (chez qui ça marche) pouvait comparer, au cas où...
Par avance merci.

**Comment by dx44** [comment]
Hello, quelle version de la carte utilisez-vous ?

**Comment by DavidTre07** [comment]
Bonjour,
version 1.9.0
![image](https://github.com/user-attachments/assets/bf2aee5e-c228-4e98-bbf8-1f27be6de840)

**Comment by WarC0zes** [comment]
> Bonjour, version 1.9.0 ![image](https://private-user-images.githubusercontent.com/10484034/368462805-bf2aee5e-c228-4e98-bbf8-1f27be6de840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzU1NzgsIm5iZiI6MTcyNjY3NTI3OCwicGF0aCI6Ii8xMDQ4NDAzNC8zNjg0NjI4MDUtYmYyYWVlNWUtYzIyOC00ZTk4LWJiZjgtMWYyN2JlNmRlODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDE2MDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZjA0ZDVjOTBkMWM3MmFiMWYxNDEwOTM0YmQzMTFkMTNmYmM4M2IyMWI4MDg3ODg0MjAyYTk5MmJjOGNiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oB8dL18b6_ki1VBDrWnawreJRB9SV1h1aUygpBg36gI)

Bonjour, cette version est obsolète, il faut installer la dernière version beta.

**Comment by DavidTre07** [comment]
Ah... Effectivement je viens d'installer la nouvelle version et ça marche maintenant.
Merci pour votre aide.

**Comment by JukeBoX87** [comment]
Bonjour,

J'ai toujours le même problème. J'ai tenté de désinstaller depuis HACS j'ai remis la dernière version beta puis un coup de CTRL+R et F5 et voilà ce que j'ai :
![weather](https://github.com/user-attachments/assets/edd85fda-0883-46a5-b89f-ac1e065c56af)
Je ne sais vraiment pas d'où peux venir le problème...

**Comment by Stef42300** [comment]
Merci de ne pas clôturer alors que le problème est toujours présent pour moi (étant donné que c'est moi qui en suis l'auteur).

**Comment by DavidTre07** [comment]
Tu pourrais tester avec la carte météo par défaut de HASS pour voir si tu as bien les prévisions.
Ceci permettra de déterminer au moins si les données sont là.

**Comment by Stef42300** [comment]
J'ai bien tout sur la carte météo classique 
![Screenshot_20240923_215050_Home Assistant](https://github.com/user-attachments/assets/67e34107-47f5-492e-8f76-13ca9911be21)
![Screenshot_20240923_215103_Home Assistant](https://github.com/user-attachments/assets/2dd3a4d8-c320-480d-9628-490a02c1bb30)
![Screenshot_20240923_215114_Home Assistant](https://github.com/user-attachments/assets/ae90c2ca-fd34-4b7e-94b3-ea9dcc968bd1)

**Comment by DavidTre07** [comment]
J'ai regardé ta config et je ne vois pas d'erreur.
Aucune idée de ce qui peut se passer chez toi.
