### ISSUE TITLE
Probleme affichage prévision jour à venir

### ISSUE THREAD

**Issue by 33Ben33127** [hacf-fr/lovelace-meteofrance-weather-card#148]
Bonjour à tous,

Bon après quelques complications j'ai enfin réussi à installer la carte.
En revanche il me manque plusieurs infos.

Voici ce que j'ai :
<img width="368" alt="image" src="https://github.com/user-attachments/assets/6c69cab9-6ca5-42d7-adf7-8735901c8833">

Il me manque donc les infos de prévisions sur les jours à venir ainsi que les alertes.

Pourriez-vous m'aider svp ?

Merci d'avance pour votre aide.
Benoit

**Comment by fdecourt** [comment]
Si cela t'intéresse, comme j'ai l'impression qu'il ne se passe plus grand chose sur ce projet, j'ai fait un fork sur la base de leur dernière version BETA, qui fonctionne bien chez moi : 

https://github.com/fdecourt/lovelace-meteofrance-weather-card

Pas sur qu'on soit dans le top du top, mais au moins, j'ai tout qui apparait !

![image](https://github.com/user-attachments/assets/ed3a5e9f-ce27-44e8-b1ec-4e8e5613fb4f)

**Comment by WarC0zes** [comment]
Bonjour, essayer la derniere release:
https://github.com/hacf-fr/lovelace-meteofrance-weather-card/releases/tag/2024.10.01

**Comment by dx44** [comment]
@WarC0zes Merci pour les actions sur ce dépôt 👍🏻 

@fdecourt Tu peux proposer une PR dans ce dépôt avec les modifications, ou encore rejoindre les membres de l'asso pour gérer ce dépôt 😉

**Comment by WarC0zes** [comment]
> @WarC0zes Merci pour les actions sur ce dépôt 👍🏻

J'ai rien fais, c'est @Giga77

**Comment by fdecourt** [comment]
> @fdecourt Tu peux proposer une PR dans ce dépôt avec les modifications, ou encore rejoindre les membres de l'asso pour gérer ce dépôt 😉

Pas du tout à l'aise avec Github, donc ne m'en voulez pas si ce n'est pas fait de la bonne manière, mais PR faites ;-)
Le version 2024.10.01 semble fonctionner, mais avec des erreurs dans Chrome (voir PR !)

**Comment by 33Ben33127** [comment]
Ahhh cool merci pour vos réponses.
Par contre un de vous pourrait m'aider svp ?

@fdecourt  Quand je veux ajouter l'adresse, je suis censé ajouter en catégorie Lovelace mais ça ne me le propose pas.
Du coup je me demande si je l'ai bien installé... quelqu'un aurait un guide d'installation de Lovelace svp ?

<img width="566" alt="image" src="https://github.com/user-attachments/assets/c2559e0f-6841-45aa-b907-ba3e12189e85">

Merci pour votre aide.
Benoit

**Comment by WarC0zes** [comment]
> Quand je veux ajouter l'adresse, je suis censé ajouter en catégorie Lovelace mais ça ne me le propose pas.

C'est nommé tableau de bord maintenant, au lieu de lovelace. Tu choisis la catégorie tableau de bord.

**Comment by 33Ben33127** [comment]
Comme je vous disais je découvre du coup j'ai voulu l'installer, ça m'affiche ça :
<img width="434" alt="image" src="https://github.com/user-attachments/assets/b00cbcf3-a60b-46df-9469-6f08f9fbadbd">

Je dois faire quoi svp les gars ? @fdecourt @WarC0zes

**Comment by Giga77** [comment]
Le dépot est installé. Maintenant va dans HACS, et cherche Météo France.
![image](https://github.com/user-attachments/assets/ffa74d1f-8818-4c62-80ed-fc5a70ac4995)

Et ensuite clique sur télécharger.

**Comment by 33Ben33127** [comment]
Génial, ça fonctionne nickel !!!

Merci beaucoup les gars pour votre aide et votre patience :-)

**Comment by dx44** [comment]
https://github.com/hacf-fr/lovelace-meteofrance-weather-card/issues/148#issuecomment-2429383346

Alors un merci à @Giga77 aussi 👍🏻
