### ISSUE TITLE
Pas d'icones animés

### ISSUE THREAD

**Issue by XTournemouli** [hacf-fr/lovelace-meteofrance-weather-card#158]
Bonjour,
J'ai installé, desinstallé puis reinstallé plusieurs fois mais j'ai toujours le meme probleme, aucun icone animé ( ou meme fixe)
j'ai testé sur tous les navigateurs,  vidé le cache etc.... je jette l'éponge

j'comprends pas :-( je jette l'éponge

![image](https://github.com/user-attachments/assets/51123406-2eb5-4b33-a805-9fc325d43ba7)

ma version HA
![image](https://github.com/user-attachments/assets/745a1cbf-c7ea-40c9-9d76-5b19aaada2a1)

la carte que j'utilise 
![image](https://github.com/user-attachments/assets/c430c636-9652-4905-ba5b-4002c687fa75)

MERCI par avance .

**Comment by Rudy74-25** [comment]
Bonjour,
J'ai le même problème. As tu réussi à avoir les icones ?
Merci.

**Comment by XTournemouli** [comment]
Oui. J'ai complètement redémarré Home Assistant et tout est apparu.

Yahoo Mail : Recherchez, organisez, maîtrisez 
 
  Le mar., janv. 7, 2025 à 23:23, ***@***.***> a écrit:   


Bonjour,
J'ai le même problème. As tu réussi à avoir les icones ?
Merci.
