### ISSUE TITLE
Revoir le README

### ISSUE THREAD

**Issue by dx44** [hacf-fr/lovelace-meteofrance-weather-card#21]
A revoir dans le README:
- Présenter l'installation via HACS et la configuration via l'éditor de la carte.
- Proposer la partie en YAML en annexe uniquement.
- Fournir une préview récente avec la vigilance pour montrer l'etendue des options

**Comment by oncleben31** [comment]
Ca devrait être une priorité.

**Comment by Axellum** [comment]
Bon, je n’écrit que le Français, et avec pleins de fautes... En plus, je ne suis pas expert avec Home Assistant ^^.
Mais bon,  j'ai essayé car même:

[](https://github.com/Axellum/weather-card/blob/Meteo-France/README.md)

Si ça vous vas comme base, je fais un PR.

**Comment by oncleben31** [comment]
Le plus dure c'est de commencer. Vas-y et nous pourrons corriger compléter et traduire.
