### ISSUE TITLE
OneHourForecast "Pas de valeur"

### ISSUE THREAD

**Issue by Axellum** [hacf-fr/lovelace-meteofrance-weather-card#24]
Prendre en charge "Pas de valeur" sur l affichage des averses sur 1h00.

**Comment by dx44** [comment]
Dans quel cas cela se produit exactement ?

**Comment by Axellum** [comment]
Cela m est arrivé plusieurs fois le même jours, sur la case 50 (ou 55) mn, pendant quelques secondes à chaque fois. Depuis je ne l est plus remarqué depuis...

**Comment by Axellum** [comment]
D’ailleurs j'ai cru voir que pour mettre des hachures il faut pas mal changer le code, perso j ai finis par mettre ["Pas de valeur", 0], .

**Comment by dx44** [comment]
Je ne pense pas qu'il y ait grand chose à changer, un style CSS et un test pour afficher un li avec ce style.

**Comment by dx44** [comment]
Même si message est anecdotique, il existe donc il faut le gérer. Jusquemenboutiste 😁
