### ISSUE TITLE
Icones de type de temps manquants

### ISSUE THREAD

**Issue by dx44** [hacf-fr/lovelace-meteofrance-weather-card#34]
La représentation du type de temps offert par météo france via des icônes n'est pas complète, des icônes sont identiques pour des types de temps différents.
Par exemple "cloudy" (nuageux) et "fog" (brouillard) ont le même icône.

**Comment by Axellum** [comment]
J ai fais un icône animé pour le brouillard et l orage pluvieux, si jamais ;).

**Comment by dx44** [comment]
Dans le même thème ?

**Comment by Axellum** [comment]
Oui https://github.com/Axellum/lovelace-meteofrance-weather-card/blob/Meteo-France/dist/icons/cloudy-day-1.svg et https://github.com/Axellum/lovelace-meteofrance-weather-card/blob/Meteo-France/dist/icons/thunder-2.svg

**Comment by Axellum** [comment]
En copie collage, donc avec ce que j'avais :).

**Comment by Axellum** [comment]
<img width="742" alt="Capture d’écran 2020-10-28 114021" src="https://user-images.githubusercontent.com/60935256/97425629-a992ad80-1912-11eb-8531-f70a57ad658f.png">

**Comment by Axellum** [comment]
Et un plus explicite pour snowy-rainy (enfin à vous de dire ^^):
https://github.com/Axellum/lovelace-meteofrance-weather-card/blob/Meteo-France/dist/icons/snowy-4.svg
<img width="79" alt="Capture d’écran 2020-10-28 141736" src="https://user-images.githubusercontent.com/60935256/97441581-2b8dd100-1929-11eb-8495-a6a59ebe69d7.png">

**Comment by Axellum** [comment]
<img width="172" alt="Capture d’écran 2020-10-29 100910" src="https://user-images.githubusercontent.com/60935256/97549172-5e3ed480-19d0-11eb-8e6f-5c081954a99d.png">
Deux en plus pour le vent (jour / nuit). Je les est nommer différemment que ceux existant. Ils sont disponible sur mon github, avec la modif du code qui vas avec.
