### ISSUE TITLE
Ajout de la carte de couverture des pluie

### ISSUE THREAD

**Issue by Axellum** [hacf-fr/lovelace-meteofrance-weather-card#38]
Je pense qu il serait judicieux d'ajouter la carte de couverture du détecteur de pluie sur 1h00, ça pourra évitez que certains ne comprennent pas pourquoi cela ne marche pas ^^.
https://www.home-assistant.io/images/integrations/meteo_france/carte-couverture-du-service.png

Enfin, si la carte est encore valide :).

**Comment by dx44** [comment]
Le lien vers la carte sur le site de météo france a été ajouté en FAQ du Readme.
