### ISSUE TITLE
Infos en 3 colonnes

### ISSUE THREAD

**Issue by cyrilphoenix71** [hacf-fr/lovelace-meteofrance-weather-card#39]
![Capture_decran_2020-10-27_093623__01](https://user-images.githubusercontent.com/18350629/97556566-f3929680-19d9-11eb-99d0-21be4bdad581.png)

Avoir les infos disposées en 2 ou 3 colonnes pour plus de lisibilites.

**Comment by dx44** [comment]
Cette demande ne sera pas prise en compte dans ce projet car cela change trop l'interface. Peut-être que quelqu'un l'implémentera dans un fork.
