### ISSUE TITLE
Modification du titre

### ISSUE THREAD

**Issue by Axellum** [hacf-fr/lovelace-meteofrance-weather-card#44]
Pensez vous qu il serait possible de modifier le titre comme ici:
https://github.com/fineemb/lovelace-colorfulclouds-weather-card

Et qu en pensez vous?

**Comment by dx44** [comment]
Alors le coté hyéroglyphe ne me parle pas. Mais techniquement on peut quasiment tout faire, surtout si cela a été fait ailleurs.
Merci de préciser ce que tu souhaites.

**Comment by Axellum** [comment]
Juste le titre sur deux lignes, avec choix du capteur pour la deuxième ligne, je pense qu il a reprit celui de la tuile fournies par HA de base.
