### ISSUE TITLE
Ajout du décompte en mn de la prochaine pluie

### ISSUE THREAD

**Issue by Axellum** [hacf-fr/lovelace-meteofrance-weather-card#48]
Comme proposé par Thettux, un timing pour connaitre le délai de la prochaine averse à l’écrit pourrait être bien. Par contre, il appel un sensor préalablement préparé sur configuration.yaml, qu'il faudrait l'intégrer dans la carte.
 Vus qu il y as l'heure de la prochaine averse sous forme de date, je suppose qu'on pourrait le reprendre pour calculer le temps d'arrivé de la pluie, mais je n'est pas réussi à le faire.
A noter que certaine carte le font sur lovelace quand on le rentre comme sensor, mais pas quand je l’insert dans dans le code de la carte lovelace-meteofrance-weather-card.

<img width="727" alt="Capture d’écran 2020-11-06 140022" src="https://user-images.githubusercontent.com/60935256/98368962-7352dd80-2038-11eb-9981-fee751ac7815.png">

**Comment by dx44** [comment]
Le sensor next_rain donne un map, nous pourrons l'utiliser pour détecter la prochaine pluie sans problème.

**Comment by dx44** [comment]
Solution apportée dans la PR #55 : ajout d'un texte précisant la prochaine pluie (suivant les tranches de prévisions dans l'heure).
