### ISSUE TITLE
Les prévision à 1 heures ne se rafraichissent pas automatiquement.

### ISSUE THREAD

**Issue by schmurtzm** [hacf-fr/lovelace-meteofrance-weather-card#58]
Hello, merci pour le boulot sur cette "card". 
J'ai remarqué que les prévision de pluie ne se rafraichissaient pas sans un reload complet de la page. Je n'ai pas encore zieuté le code mais c'est assez gainant pour tout ce qui est tablettes murales, etc.

**Comment by dx44** [comment]
Salut, je ne remarque pas se soucis. La carte est rafraichie automatiquement par HA.

**Comment by schmurtzm** [comment]
Elle est rafraichie sans presser F5 ? 
Je remarque que ce n'est pas systématique en effet... C'est comme s'il y'avait un timer assez important pour le refresh...

Je ne sais pas d'ou ça vient mais j'arrive à le reproduire sur Home Assistant IOS et sur Firefox (Windows).

J'ai de la "chance" il pleut dans 20 minute, pratique pour tester :D 

Sinon procédure pour le reproduire : 
 - ouvrir un onglet de navigateur affichant la pluie dans l'heure
 - aller dans Developer Tools -> rechercher "sensor.******_next_rain"
 - modifier l'une des value en "Pluie modérée" -> ce n'est pas rafraichie en live ni sur firefox, ni sur ios.
 - Pressez F5 pour rafraichir la page et la card est bien rafraichie

Si on utilise une autre card c'est bien rafraichi.

**Comment by dx44** [comment]
La manipulation que tu présentes modifie la valeur de next_rain uniquement dans la session de ton navigateur, tu ne modifies pas le sensor sur HA.
Ensuite je ne saurais dire exactement quand la carte est rafraichie exactement. Il me semble quand un sensor change dans HA (mais pas dans le navigateur).

**Comment by schmurtzm** [comment]
Non la méthode "set state" qui est appelée change réellement l'état de l'entité dans Home Assistant, pas juste dans le navigateur... C'est d'ailleurs très pratique pour tester le déclenchement d'une automation par exemple.
Vous avez fait comment pour tester la partie pluie du coup ? Vous avez attendu qu'il pleuve  :sweat_smile: ? 

D'ailleurs l'ancienne version d'Axellum est rafraichie en live, (après quelques modifs pour être compatible avec la nouvelle intégration météo france. D'ailleurs leur idée de mettre des libellés pour les niveaux de pluie plutôt que de conserver les numéros fournis par l'API franchement je n'ai pas compris...)

Non ça devrait être rafraichi en live comme n'importe quel autre sensor et ce n'est pas le cas.  Je ne suis pas fortiche en js mais il y'a quelque part dans ce code quelque chose qui fait que cette card n'est pas rafraichie comme elle le devrait.

**Comment by Axellum** [comment]
Donc oui Schmurtzm, il faut un délais de 2 - 3 mn à la carte pour s'actualiser, je ne pense pas que ce soit un gros problème en réel, et cela prend moins de ressources. Mais à voir :)

**Comment by dx44** [comment]
> Non la méthode "set state" qui est appelée change réellement l'état de l'entité dans Home Assistant,...
Où trouves-tu cette méthode ???

> Vous avez fait comment pour tester la partie pluie du coup ? Vous avez attendu qu'il pleuve 😅 ?
Non, en changeant les attributs du sensor dans HA 😃 

> Du coup je pense que le code surveille les changements d'un sensor ...
Le code de la carte s'occupe simplement d'afficher une mise en forme des entités. Il n'y a pas de listener sur le changement de quoi que ce soit dans ce code!

**Comment by schmurtzm** [comment]
> Donc oui Schmurtzm, il faut un délais de 2 - 3 mn à la carte pour s'actualiser
>
Ah donc tu sais d'ou ça vient ? 

>  je ne pense pas que ce soit un gros problème en réel, et cela prend moins de ressources. Mais à voir :)
>
Ahah vu le bouzin (je parle de HA), je ne pense pas que l'on soit à un rafraichissement près et quand on parle d'une météo précise à 5 minutes près (car c'est le cas, je ne sais pas si vous avez fait gaf mais cette prévision est assez incroyable de précision) alors ça a sans doutes son importance (mais bon je dois être un peu maniaque :D ). D'ailleurs c'est quand même dommage d'avoir un rafraichissment hyper réactif sur la météo de demain et pas sur la météo à 5 minutes, non ? ;)

> Où trouves-tu cette méthode ???
>
Juste là, tu vois c'est trop pratique pour tester, tu changes tes values, tu fais un "set state" et ensuite c'est écrasé lors de la prochaine update du sensor. (Mais je suppose que l'on parle de la même chose ?)
<img src="https://user-images.githubusercontent.com/7110113/99044670-6b42f280-2590-11eb-93b4-da4b4e7c0532.png" width="200" height="200">

> Le code de la carte s'occupe simplement d'afficher une mise en forme des entités. Il n'y a pas de listener sur le changement de quoi que ce soit dans ce code!
>
Il doit y avoir une raison, bon j'y connais rien en js ou en dev de custom card donc je ne trouve pas pour l'instant ...mais je cherche 😅 !

**Comment by Axellum** [comment]
Non je ne sait pas d’où ça vient, je suis une bille en js lol.

**Comment by schmurtzm** [comment]
Ahah on va trouver !
Je pense que je chauffe 👍   :  https://github.com/hacf-fr/lovelace-meteofrance-weather-card/blob/333681297e740b4ca087b0288852172dcbea96a2/dist/meteofrance-weather-card.js#L115

**Comment by dx44** [comment]
> Juste là, tu vois c'est trop pratique pour tester, ...

Oui c'est bien ce que j'utilise. Et je n'avais pas bien lu ton message précédent car tu précises bien :  Developer Tools -> rechercher "sensor.******_next_rain"

> Je pense que je chauffe

Pas spécialement, c'est une méthode appelée par shoudlUpdate qui elle même est appelé par Lovelace pour savoir si la carte doit être affichée/rafraichie (évite d'afficher une carte qui n'a pas encore de config).
D'ailleurs les 3 premières lignes de cette méthode indique toujours 'true' si une config existe, ce qui est toujours le cas.

Le rafraichissement est dépendant de HA et de l'entité Weather.

**Comment by schmurtzm** [comment]
> Le rafraichissement est dépendant de HA et de l'entité Weather.
>
N'y a t-il donc pas moyen de le faire dépendre également de l'entité next_rain ?

**Comment by Axellum** [comment]
J ai peut être trouvé: (ligne 120)

  const oldHass = changedProps.get("hass");
  if (oldHass) {
    return (
      oldHass.states[element._config.entity] !==
      element.hass.states[element._config.entity] ||
      oldHass.states["sun.sun"] !== element.hass.states["sun.sun"]
      || oldHass.states["sensor.capbreton_next_rain"] !== element.hass.states["sensor.capbreton_next_rain"]
    );
  }

**Comment by dx44** [comment]
@schmurtzm  Puisque tu aimes lire le code :) , voici qui va répondre à une bonne partie de tes questions :

* Les [intervalles de polling](https://github.com/hacf-fr/home-assistant-core/blob/d47b3a5f4406866e42d64aabc3395d935016d96d/homeassistant/components/meteo_france/__init__.py#L29-L30) dans l'intégration de Météo France,
* et le [principe de polling](https://developers.home-assistant.io/docs/integration_fetching_data) dans HA
* et pour aller plus en profondeur avec [ce billet](https://developers.home-assistant.io/blog/2019/05/22/internet-of-things-and-the-modern-web/).

@Axellum Cette partie de code est traitée uniquement si il n'y a pas de config. Regarde les 3 premières de la méthode :)

**Comment by Axellum** [comment]
Hum, la maj se fais en direct pourtant avec cette modification, ou alors j ai beaucoup de chance ^^. Dites moi alors ce que ça donne chez vous.

**Comment by Axellum** [comment]
![test](https://user-images.githubusercontent.com/60935256/99062467-57ed5280-25a3-11eb-9fe8-518364343cd7.gif)

**Comment by dx44** [comment]
@Axellum Pour mes tests, la maj est faite dans les 5 min. max. mais pas instantanément comme tu le montres. Ou alors il y a un paramètre dans HA qui pousse directement et je n'ai pas vu ça ... je suis loin de tout connaître dessus 😄 😄 (très loin).

**Comment by Axellum** [comment]
Harff, je doit louper un truc du coup (c’était déjà 5 mn max)... Je regarderai tout à l heure si j ai changer autre choses... Mais je ne pense pas!

**Comment by schmurtzm** [comment]
> 
> 
> @schmurtzm Puisque tu aimes lire le code :) , voici qui va répondre à une bonne partie de tes questions :
> 
>     * Les [intervalles de polling](https://github.com/hacf-fr/home-assistant-core/blob/d47b3a5f4406866e42d64aabc3395d935016d96d/homeassistant/components/meteo_france/__init__.py#L29-L30) dans l'intégration de Météo France,
> 
Cool, merci ! 5 minutes OK c'est cohérent, ça ne servirait à rien de faire plus.
>     * et le [principe de polling](https://developers.home-assistant.io/docs/integration_fetching_data) dans HA
> 
Je ne suis pas sur d'aimer lire le code à ce point, ce qui est certain c'est que cette partie fonctionne admirablement bien.
>     * et pour aller plus en profondeur avec [ce billet](https://developers.home-assistant.io/blog/2019/05/22/internet-of-things-and-the-modern-web/).
> 
Excellent ticket, ce mec est bon ;) 
Bon après ce qui est certain et tiré de leur doc également :  

> Whenever the state changes, the component will have to update itself to represent the latest state. 
>
Et là clairement ce n'est pas le cas.

> @Axellum Cette partie de code est traitée uniquement si il n'y a pas de config. Regarde les 3 premières de la méthode :)

Je pense quand même que c'est la bonne piste. Cependant je galère à faire mes modifs dans le js et à en voir les effets... J'ai beau cleaner le cache de mon navigateur, il y'a une subtilité que je ne saisie pas...

**Comment by Axellum** [comment]
@schmurtzm T as bien supprimé le fichier meteofrance-weather-card.js.gz?

**Comment by schmurtzm** [comment]
Oui... Ah j'ai compris, c'est mon Nginx qui faisait du "cache assets" , cochonsté je ne comprenais rien !

**Comment by schmurtzm** [comment]
Bon du coup je confirme que ta modif fonctionne Axellum !
Reste à rendre ça plus générique ;)

**Comment by dx44** [comment]
@schmurtzm j'ai pu observé le même effet de délai entre le sensor et la carte (il pleut en ce moment chez moi :D). Et je passe aussi par un nginx en reverse (Synology), c'est très certainement une gestion de cache de mon coté aussi !!! Bon il faut que je regarde comment gérer cela.

**Comment by schmurtzm** [comment]
Oui et non : le problème du cache Nginx fait que les modifs que l'on effectue dans le js ne sont pas répercutées lors des tests. Pour être certain que mes modifs étaient prises en compte je me suis amusé à modifier le mot "actuellement" ligne 358 en vérifiant à chaque fois que c'était bien répercuté dans lovelace.

Une fois que les mises à jour en live fonctionnent bien tu peux réactiver le cache Nginx tu n'auras plus de soucis : le problème vient du code de d'update de la custom card, pas de Nginx ;)

**Comment by dx44** [comment]
> ... je me suis amusé à modifier le mot "actuellement" ...

Je n'ai pas compris le principe de ton test

**Comment by Axellum** [comment]
Avec une horloge sur la carte, je vois que cela ne fais pas de maj toute les 30s mais juste si _next_rain change. Par contre, pour faire en sorte que ce soit générique, j'ai peur que cela soit trop complexe pour moi :).

**Comment by dx44** [comment]
@schmurtzm Et bien tu as bien fait d'insister et moi de même. Cela m'a permit de comprendre en un peu plus HA et Lovelace :)
Pour faire simple, la méthode que tu indiques est bien appelée lors du refresh de la carte, là dessus je n'avais pas de doute, par contre les quelques tests de j'ai fait montré un `changedProps.has('_config')` à `true` ... donc pour moi ça passe toujours !!!
Et bien non, cela a dû être un cas particulier et je me suis tout simplement fourvoyé. Bref, je ne lache pas le morceau non plus et en approfondissant j'ai compris mon erreur 😁 .
Il me reste à corriger 😎
