### ISSUE TITLE
Forecast heure par heure ?

### ISSUE THREAD

**Issue by prigal** [hacf-fr/lovelace-meteofrance-weather-card#60]
Bonjour,

Je viens d'ajouter cette card sur mon home assistant car madame avait retoqué le module "par défaut" :) 

Du coup, c'est un peu mieux, mais pas encore "pratique" pour estimer correctement la journée pour habiller les enfants le matin ! (...il est ou le temps où nos grands parents ouvraient une fenêtre, respirait un grand coup, regardaient au loin et disaient "il va pleuvoir et faire froid, habillez-vous").

Toute cette introduction pour savoir si on peut via meteo france obtenir un forecast heure par heure comme le fait google avec un petit graphique ? 

![Capture d’écran de 2020-11-12 21-08-46](https://user-images.githubusercontent.com/895267/98990931-6bf56d80-252b-11eb-9248-14d6c168f1a5.png)

Merci !

**Comment by prigal** [comment]
En fait idéalement il faudrait pouvoir paramétrer le type de forecast "hourly" ou "daily" ainsi au lieu de voir des jours on verrait des heures à la place dans la carte 

![Capture d’écran de 2020-11-12 21-14-48](https://user-images.githubusercontent.com/895267/98991597-59c7ff00-252c-11eb-9f57-c35f2601da14.png)

**Comment by dx44** [comment]
Salut @prigal , c'est déjà possible mais cela se gère au niveau de l'intégration Météo France où tu précises si tu veux la prévision à l'heure ou à la journée. Pour le moment c'est l'un ou l'autre.

**Comment by prigal** [comment]
Omg je suis passé totalement à côté :) thx @dx44

**Comment by prigal** [comment]
![Capture d’écran de 2020-11-12 22-19-38](https://user-images.githubusercontent.com/895267/98997693-2fc70a80-2535-11eb-89fa-69141262f15a.png)

Du coup le trick pour avoir les 2 à la fois, c'est de prendre le village d'à côté :)

**Comment by dx44** [comment]
Tu peux faire une demande d'amélioration sur le github de HA pour l'intégration Météo France ;)

**Comment by prigal** [comment]
Yes done https://community.home-assistant.io/t/meteo-france-integration-hourly-forecast/244679.

NB : pas sur le GH car ils redirect vers le forum pour les feature request.
