### ISSUE TITLE
Remplacer la température de base par un sensor perso

### ISSUE THREAD

**Issue by tonioa** [hacf-fr/lovelace-meteofrance-weather-card#65]
Ca serait sympa de pouvoir remplacer la température de base fourni par météo france par son propre sensor perso, avec une sonde extérieure, on aurait la véritable température. Pour l'instant j'affiche ce sensor en secondaire en dessous du principale

**Comment by dx44** [comment]
Une possibilité actuellement est d'utiliser le sensor perso dispo juste en dessous de la température.

**Comment by tonioa** [comment]
Oui pour le moment c'est ce que j'ai fait, merci

**Comment by dx44** [comment]
La carte reste uniquement sur les données de Météo France.
Je clos cette Issue !
