### ISSUE TITLE
Masquer la zone précipitation dans l’heure si il n’y a pas de précipitation prévu

### ISSUE THREAD

**Issue by tonioa** [hacf-fr/lovelace-meteofrance-weather-card#66]
Masquer la zone précipitation dans l’heure si il n’y a pas de précipitation prévu tout comme les prévisions d'alertes

**Comment by dx44** [comment]
Nous prenons le partie pris d'avoir une carte de taille fixe pour qu'elle soit intégrable dans des tableaux de bords sur mesure. Dans ce sens cette proposition n'est pas envisagée.
La partie Alerte sera motifiée dans ce sens dans une prochaine version.
