### ISSUE TITLE
Consommation CPU

### ISSUE THREAD

**Issue by cbernet** [hacf-fr/lovelace-meteofrance-weather-card#77]
Bonjour ! tout d'abord merci beaucoup pour cette carte, qui montre les bonnes infos, et qui est vraiment jolie. 

Par contre, il me semble que l'affichage de la carte demande beaucoup de CPU. Sur un macbook pro récent et avec Firefox, l'affichage de la carte prend entre 50 et 100 % d'un CPU. Il suffit que je l'enlève pour retomber à une utilisation normale. 

Voyez-vous la même chose ? je peux donner plus d'infos sur mon système, et tester avec d'autres navigateurs si besoin.

**Comment by Neonox31** [comment]
Hello,

Idem de mon côté, c'est à cause des icônes animées, tu peux les remplacer par des fixes en suivant ce lien : https://github.com/bramkragten/weather-card/issues/46#issuecomment-622127197

**Comment by izeau** [comment]
On peut remplacer les icônes animées par des icônes fixes assez simplement en configurant _Icons location_ à `https://cdn.jsdelivr.net/gh/hacf-fr/lovelace-meteofrance-weather-card@latest/icons/static/`.

**Comment by Axellum** [comment]
Salut,
Si jamais, il y as aussi deux autre jeux d’icônes compatible sur mon git:
[Icônes blanc fixe](https://github.com/Axellum/lovelace-meteofrance-weather-card/tree/Meteo-France/dist)
