### ISSUE TITLE
Carte qui disparait depuis la dernière mise à jour de HA

### ISSUE THREAD

**Issue by Balbao** [hacf-fr/lovelace-meteofrance-weather-card#83]
Depuis la dernière mise à jour de HA, soit les infos sont indiquées comme " undefined " ou alors la carte disparait. Obligé de redémarrer HA, et cela se reproduit peut de temps après. Je n'avais aucun problème avant cette mise à jour.

**Comment by dx44** [comment]
Merci de préciser la version de HA et la release de la carte.
Tout comme une capture d'écran du problème !

**Comment by dx44** [comment]
Par de retour sur cette issue. Clôture !
