### ISSUE TITLE
optimisation carte

### ISSUE THREAD

**Issue by Fromthenuts** [hacf-fr/lovelace-meteofrance-weather-card#87]
Bonjour à tous,

Merci beaucoup pour la carte, elle est vraiment top, par contre je me pose la question de savoir si il est possible d'arriver à ce résultat avec les fonctionnalités disponibles, c'est à dire :

- temps actuels avec toutes les constantes (ça ok)
- prévisions sur la journée heure par heure (sur 8h) (ça ok aussi je pense)
- prévisions des deux prochains jours détaillés (matin, après-midi, soirée, nuit) (ça je sais pas si c'est possible..., exemple issu du site de météofrance, je sais pas si l'api donne ces infos la)
- prévisions jours par jours pendant les 8 prochains jours (ça ok aussi normalement)

En image, la carte qui serait parfaite pour moi... :

![carte meteociel voulue](https://user-images.githubusercontent.com/96888189/151446485-c74288ba-0afe-45d2-ab1c-9c5b49c53c54.jpg)

Merci de vos retours !

FtN

**Comment by Axellum** [comment]
Salut,
Je ne pense que l on puisse mettre les détails des trois prochain jours (pas vus dans l'api).
Par contre feinté en mettant deux cartes météo, une en heure et l'autre en jours, en ajoutant une commune proche de la tienne dans l'intégration météo France. Par exemple:
 
<img width="393" alt="Capture d’écran 2023-03-13 195336" src="https://user-images.githubusercontent.com/60935256/224805990-570ace81-de56-49e8-8b3f-58156f89bd0e.png">

**Comment by dx44** [comment]
La solution de 2 cartes est à utiliser.
