### ISSUE TITLE
Pas de Prévision Daily

### ISSUE THREAD

**Issue by PatLazuli** [hacf-fr/lovelace-meteofrance-weather-card#89]
Bonjour,

Je n'arrive pas a avoir les prévisions en daily, j'ai tout désinstallé et réinstallé. "One hour forecast" est bien désactivé. Une idée ? Merci

**Comment by PatLazuli** [comment]
Re 
Je répond à moi même. il faut aller dans configuration=>Devices&Services=>météo france.

Merci

**Comment by nash68** [comment]
> Re Je répond à moi même. il faut aller dans configuration=>Devices&Services=>météo france.
> 
> Merci

Merci 👍
