### ISSUE TITLE
Ajouter 'vitesse de vent' 

### ISSUE THREAD

**Issue by vingerha** [hacf-fr/lovelace-meteofrance-weather-card#90]
J'aime bien votre taff que j'utilise souvent....merçi !
Ma demande : pourriez vous ajouter la vitesse de vent dans les détails (jours/heure)? Les données sont là mais la carte ne le couvre pas (pour l'instant)
Je suis aussi heureux de vous presenter un pull-request mais je voix déjà plusieurs qui ne sont pas honnorés
Assui, si vous n'êtes plus active sur cet objet, svp de le clarifier

**Comment by sigalou** [comment]
Bonjour à tous,

Je rebondis sur le message de vingerha.
Habitant dans le sud, je suis particulièrement intéressé par l'information vent de la prévision horaire.
Je suis prêt à m'impliquer dans le code si j'ai le feu vert d'un admin qui valide le principe de l'action.
Je verrai bien un paramètre avec une ligne de plus pour le vent ou si ce n'est pas possible, une inversion avec la pluie (qui resterait par défaut).
Qu'en pensez vous ?
Merci

**Comment by dx44** [comment]
@vingerha La PR présentée n'était pas adaptée. Merci d'en refaire une plus suscinte.

**Comment by vingerha** [comment]
@dx44 Bonjour, j'ai refait (et beaucoup plus simple) l'ajout de la vitesse de vent
Ensuite, j'ai aussi un fix pour les icones (dans la nuit), est-ce que je base cet PR sur la version avec ou la version sans vitesse de vent?
M'excuse la question mais pas je ne suis trops developeur

**Comment by dx44** [comment]
Hello, un PR pour chaque correction ou amélioration 👍🏻
